/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SomeHub: typeof import('./src/components/SomeHub/index.vue')['default']
    VueMarkdown: typeof import('./src/components/MarkDown/VueMarkdown.vue')['default']
  }
}
